# Generated by Django 5.0.2 on 2024-02-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='department',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='home',
            name='year',
            field=models.CharField(max_length=25),
        ),
    ]
